services:
- type: web
  name: fastapi-app
  env: docker
  dockerfilePath: ./fastapi/Dockerfile
  envVars:
    - key: SOME_ENV_VARIABLE
      value: some_value
  ports:
    - 8000

- type: web
  name: streamlit-app
  env: docker
  dockerfilePath: ./streamlit/Dockerfile
  envVars:
    - key: SOME_OTHER_ENV_VARIABLE
      value: another_value
  ports:
    - 8501
