version: '3'

# services — Defines the services that make up the application.
services:
  finpy-streamlit-app:
    build: finpy-streamlit-app
    ports:
      - 8501:8501
    depends_on:
      - finpy-api
    volumes:
      - ./finpy-streamlit-app:/app
      - ./storage:/storage
    environment:
      - BACKEND_URL=http://finpy-api:8080

  finpy-api:
    build: finpy-api
    ports:
      - 8080:8080
    volumes:
      - ./finpy-api:/app
      - ./storage:/storage
